version: "3"

services:
  postgres:
    image: timescale/timescaledb-ha:pg14-latest
    environment:
      POSTGRES_PASSWORD: "6QUBYF5wegdWaf4PR"
      POSTGRES_USER: envoys
    volumes:
      - ./db:/docker-entrypoint-initdb.d
    ports:
      - "5432:5432"

  rabbitmq:
    image: rabbitmq:latest
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    ports:
      - "15675:15675"
    command: bash -c "rabbitmq-plugins enable --offline rabbitmq_management rabbitmq_web_stomp rabbitmq_web_mqtt rabbitmq_shovel rabbitmq_shovel_management && rabbitmq-server"

  redis:
    image: redis:latest
    ports:
      - "6379:6379"